prometheus:
  image: prom/prometheus:v2.54.1
  port: 9090
  retention: 15d
  serviceType: ClusterIP

loki:
  image: grafana/loki:2.9.8
  port: 3100
  serviceType: ClusterIP

grafana:
  image: grafana/grafana:11.3.0
  port: 3000
  serviceType: ClusterIP
